Repository AdobeDocs/commerce-php, pull requests merged in 2022-08, with the labels that each got.

#42 Port 2.4.5 changes to PHP Developer guide
  src/pages/development/components/message-queues/async-configuration.md
  src/pages/development/components/message-queues/bulk-operations-example.md
  src/pages/development/components/message-queues/configuration.md
Labels: major update, 2.4.5

#44 Updated Module Reference Guide data for the 2.4.5 release
  src/data/navigation/sections/module_reference.js
  src/pages/module-reference/module-admin-adobe-ims.md
  src/pages/module-reference/module-adobe-ims-api.md
  src/pages/module-reference/module-adobe-ims.md
  src/pages/module-reference/module-adobe-stock-client-api.md
  src/pages/module-reference/module-amqp-store.md
  src/pages/module-reference/module-catalog-url-rewrite.md
  src/pages/module-reference/module-csp.md
  src/pages/module-reference/module-developer.md
  src/pages/module-reference/module-google-gtag.md
  src/pages/module-reference/module-graph-ql-cache.md
  src/pages/module-reference/module-graph-ql.md
  src/pages/module-reference/module-grouped-catalog-inventory.md
  src/pages/module-reference/module-grouped-import-export.md
  src/pages/module-reference/module-grouped-product-graph-ql.md
  src/pages/module-reference/module-grouped-product.md
  src/pages/module-reference/module-integration.md
  src/pages/module-reference/module-re-captcha-gift-card.md
  src/pages/module-reference/module-re-captcha-invitation.md
  src/pages/module-reference/module-re-captcha-multiple-wishlist.md
  src/pages/module-reference/module-wishlist-graph-ql.md
Labels: major update, 2.4.5

#46 Editorial fix
  src/pages/index.md
Labels: editorial

#48 Added instructions on magneto-coding-standard execution and configuration for PHPStorm
  src/pages/coding-standards/index.md
Labels: major update, internal

#50 Migrate site to use Yarn 3
  .env.example
  .github/linters/.markdown-lint.yml
  .github/linters/.yaml-lint.yml
  .github/scripts/get-path-prefix.js
  .github/workflows/deploy.yml
  .github/workflows/github-pages.yml
  .github/workflows/test-pull-request.yml
  .gitignore
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/releases/yarn-3.2.2.cjs
  .yarnrc.yml
  README.md
  package-lock.json
  package.json
  yarn.lock
Labels: dependencies, enhancement, maintenance, internal
