Repository AdobeDocs/commerce-php, pull requests merged in 2022-10, with the labels that each got.

#70 COMDOX-327: Migrate Advanced Reporting from magento/devdocs
  src/data/navigation/sections/development.js
  src/pages/_images/analytics_xsd.svg
  src/pages/_images/reports_xsd.svg
  src/pages/development/advanced-reporting/data-collection.md
  src/pages/development/advanced-reporting/index.md
  src/pages/development/advanced-reporting/modules.md
  src/pages/development/advanced-reporting/report-xml.md
Labels: migration

#72 COMDOX-299: Migrate Backward-incompatible changes from magento/devdocs
  src/data/navigation/sections/development.js
  src/pages/_includes/backward-incompatible-changes/b2b/2.4.0-2.4.1.md
  src/pages/_includes/backward-incompatible-changes/b2b/2.4.1-2.4.2.md
  src/pages/_includes/backward-incompatible-changes/b2b/2.4.2-2.4.3.md
  src/pages/_includes/backward-incompatible-changes/b2b/2.4.3-2.4.3-p1.md
  src/pages/_includes/backward-incompatible-changes/b2b/2.4.3-2.4.4.md
  src/pages/_includes/backward-incompatible-changes/b2b/2.4.4-2.4.5.md
  src/pages/_includes/backward-incompatible-changes/commerce/2.3.0-2.4.0.md
  src/pages/_includes/backward-incompatible-changes/commerce/2.4.0-2.4.1.md
  src/pages/_includes/backward-incompatible-changes/commerce/2.4.1-2.4.2.md
  src/pages/_includes/backward-incompatible-changes/commerce/2.4.2-2.4.3.md
  src/pages/_includes/backward-incompatible-changes/commerce/2.4.3-2.4.3-p1.md
  src/pages/_includes/backward-incompatible-changes/commerce/2.4.3-2.4.4.md
  src/pages/_includes/backward-incompatible-changes/commerce/2.4.4-2.4.5.md
  src/pages/_includes/backward-incompatible-changes/open-source/2.3.0-2.4.0.md
  src/pages/_includes/backward-incompatible-changes/open-source/2.4.0-2.4.1.md
  src/pages/_includes/backward-incompatible-changes/open-source/2.4.1-2.4.2.md
  src/pages/_includes/backward-incompatible-changes/open-source/2.4.2-2.4.3.md
  src/pages/_includes/backward-incompatible-changes/open-source/2.4.3-2.4.3-p1.md
  src/pages/_includes/backward-incompatible-changes/open-source/2.4.3-2.4.4.md
  src/pages/_includes/backward-incompatible-changes/open-source/2.4.4-2.4.5.md
  src/pages/development/backward-incompatible-changes/highlights.md
  src/pages/development/backward-incompatible-changes/index.md
  src/pages/development/backward-incompatible-changes/reference.md
  src/pages/development/components/view-models.md
Labels: migration

#74 Fix grammar
  src/pages/module-reference/module-shared-catalog.md
Labels: editorial

#76 Updated code sample
  src/pages/development/components/message-queues/index.md
Labels: technical

#79 Update theme, link checker, yarn
  .github/workflows/test-pull-request.yml
  .yarn/releases/yarn-3.2.2.cjs
  .yarn/releases/yarn-3.2.4.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: bug, dependencies
