Repository AdobeDocs/commerce-php, pull requests merged in 2023-08, with the labels that each got.

#177 Update doc according to the changes introduced in ACP2E-2114
  src/pages/development/backward-incompatible-changes/highlights.md
Labels: major update, internal, 2.4.7

#179 Link to the Advanced Reporting troubleshooter in the KB
  src/pages/development/advanced-reporting/index.md
Labels: editorial, internal

#180 Fix "Indexer Status" table markdown formatting
  src/pages/development/components/indexing/index.md
Labels: editorial
