Repository AdobeDocs/commerce-php, pull requests merged in 2023-01, with the labels that each got.

#100 ACP2E-1442: Update some misspellings in the documentation
  src/pages/architecture/basics/frontend-customization.md
  src/pages/development/components/view-models.md
Labels: editorial, internal

#101 COMDOX-406: Add 2.4.6-beta BIC highlights
  src/pages/development/backward-incompatible-changes/highlights.md
Labels: major update, 2.4.6

#53 Changed Url to UrlInterface in Actions.php class
  src/pages/development/components/add-admin-grid.md
Labels: technical

#54 Update add-shipping-carrier.md
  src/pages/tutorials/frontend/custom-checkout/add-shipping-carrier.md
Labels: technical

#104 COMDOX-328: Port 2.4.6-develop changes from magento-commerce/devdocs
  src/pages/development/components/searching-with-repositories.md
Labels: editorial, 2.4.6

#107 Fix capitalization error
  src/pages/development/components/plugins.md
Labels: editorial
