Repository AdobeDocs/commerce-php, pull requests merged in 2023-10, with the labels that each got.

#198 ACP2E-2419: Document the updated behavior of isEmailAvailable endpoint in 2.4.7-b1
  src/pages/development/backward-incompatible-changes/highlights.md
Labels: technical, internal

#202 Update Backward incompatible changes reference docs
  src/_includes/backward-incompatible-changes/b2b/2.4.6-2.4.7-beta2.md
  src/_includes/backward-incompatible-changes/commerce/2.4.6-2.4.7-beta2.md
  src/_includes/backward-incompatible-changes/open-source/2.4.6-2.4.7-beta2.md
  src/pages/development/backward-incompatible-changes/reference.md
Labels: major update, internal, 2.4.7-beta2

#203 Updated Module Reference Guide data for the 2.4.7-beta2 release
  src/data/navigation/sections/module_reference_beta.js
  src/pages/module-reference-beta/module-admin-adobe-ims.md
  src/pages/module-reference-beta/module-application-server-new-relic.md
  src/pages/module-reference-beta/module-commerce-backend-uix.md
  src/pages/module-reference-beta/module-customer-segment-graph-ql.md
  src/pages/module-reference-beta/module-elasticsearch.md
  src/pages/module-reference-beta/module-graph-ql-resolver-cache.md
  src/pages/module-reference-beta/module-import-json-api.md
  src/pages/module-reference-beta/module-import-json.md
  src/pages/module-reference-beta/module-order-cancellation-graph-ql.md
  src/pages/module-reference-beta/module-order-cancellation.md
  src/pages/module-reference-beta/module-quick-checkout-admin-panel.md
  src/pages/module-reference-beta/module-quick-checkout.md
  src/pages/module-reference/module-admin-adobe-ims.md
Labels: major update, internal, 2.4.7-beta2

#201 Add links to extensibility docs
  src/pages/development/components/events-and-observers/index.md
Labels: editorial, internal, 2.4.7-beta2

#204 Rename the test:links task
  .github/workflows/test-pull-request.yml
  package.json
Labels: maintenance

#205 Fix broken link
  src/_includes/page-cache-checklist.md
Labels: editorial, internal

#206 Upgrade test-pull-request workflow
  .github/workflows/test-pull-request.yml
  package.json
Labels: maintenance
