Repository AdobeDocs/commerce-php, pull requests merged in 2023-03, with the labels that each got.

#118 Fix indexing workflow failure
  .github/workflows/index.yml
Labels: bug

#119 Prepare for required workflow
  .github/linters/.markdownlint.yml
  .github/super-linter.env
  .github/workflows/test-pull-request.yml
  .markdownlint.yml
  package.json
  yarn.lock
Labels: maintenance

#120 Sync 2.4.6-develop
  .github/CONTRIBUTING.md
  .github/linters/.markdownlint.yml
  .github/super-linter.env
  .github/workflows/deploy.yml
  .github/workflows/github-pages.yml
  .github/workflows/index.yml
  .github/workflows/test-pull-request.yml
  .markdownlint.yml
  package.json
  src/pages/architecture/basics/frontend-customization.md
  src/pages/development/components/add-admin-grid.md
  src/pages/development/components/message-queues/bulk-operations.md
  src/pages/development/components/plugins.md
  src/pages/development/components/view-models.md
  src/pages/tutorials/frontend/create-custom-widget.md
  src/pages/tutorials/frontend/custom-checkout/add-shipping-carrier.md
  yarn.lock
Labels: maintenance, 2.4.6

#121 Revert the test-pull-request workflow
  .github/workflows/test-pull-request.yml
Labels: maintenance

#123 Change indexing cron to monthly
  .github/workflows/index.yml
Labels: maintenance

#125 Fix deployment workflow
  .github/workflows/deploy.yml
Labels: bug

#127 Backward incompatible changes for 2.4.6
  src/pages/_includes/backward-incompatible-changes/b2b/2.4.5-2.4.6.md
  src/pages/_includes/backward-incompatible-changes/commerce/2.4.5-2.4.6.md
  src/pages/_includes/backward-incompatible-changes/open-source/2.4.5-2.4.6.md
  src/pages/development/backward-incompatible-changes/reference.md
Labels: major update, 2.4.6

#131 GH-130: Add missing 2.4.6 BIC highlights
  src/pages/development/backward-incompatible-changes/highlights.md
Labels: major update, 2.4.6

#132 COMDOX-588: Standardized README
  README.md
Labels: maintenance
