Repository AdobeDocs/commerce-php, pull requests merged in 2023-06, with the labels that each got.

#160 Fix GitHub pages workflow
  .github/workflows/github-pages.yml
Labels: bug, maintenance

#161 Fix GH Pages workflow
  .github/workflows/github-pages.yml
Labels: bug, maintenance, internal

#162 Fix unpleasant grammar mistakes
  src/pages/development/components/indexing/index.md
Labels: editorial

#164 Update BIC reference data
  src/pages/_includes/backward-incompatible-changes/b2b/2.4.6-2.4.7-beta1.md
  src/pages/_includes/backward-incompatible-changes/commerce/2.4.6-2.4.7-beta1.md
  src/pages/_includes/backward-incompatible-changes/open-source/2.4.6-2.4.7-beta1.md
  src/pages/development/backward-incompatible-changes/reference.md
Labels: major update, internal, 2.4.7-beta1

#166 Increase max_old_space_size for builds
  .github/workflows/index.yml
  .github/workflows/publish.yml
  .github/workflows/stage.yml
  .github/workflows/test-pull-request.yml
Labels: bug, maintenance

#168 Update database-caching.md
  src/pages/development/cache/partial/database-caching.md
Labels: editorial
