Repository AdobeDocs/commerce-php, pull requests merged in 2023-05, with the labels that each got.

#146 fix: grammar and typo
  src/pages/development/components/events-and-observers/index.md
Labels: editorial

#154 COMDOX-620: Added PHP app server BIC highlight
  src/pages/development/backward-incompatible-changes/highlights.md
Labels: major update, 2.4.7-beta1

#157 Make add-to-project-board a reusable workflow
  .github/workflows/add-to-project-board.yml
  .github/workflows/add-to-project_job.yml
Labels: maintenance

#159 Fix text errors
  src/pages/best-practices/admin/placement-and-design.md
  src/pages/best-practices/phpstorm/run-configuration.md
  src/pages/best-practices/phpstorm/upgrade-compatibility-tool.md
  src/pages/coding-standards/docblock.md
  src/pages/coding-standards/jquery-widgets.md
  src/pages/coding-standards/js-docblock.md
  src/pages/coding-standards/js.md
  src/pages/development/backward-incompatible-changes/highlights.md
  src/pages/development/backward-incompatible-changes/index.md
  src/pages/development/cache/page/private-content.md
  src/pages/development/cli-commands/naming-guidelines.md
  src/pages/development/components/declarative-schema/patches.md
Labels: maintenance, editorial, internal
