Repository AdobeDocs/commerce-php, pull requests merged in 2023-02, with the labels that each got.

#109 Update theme, gatsby, and yarn up
  .github/CONTRIBUTING.md
  .github/workflows/github-pages.yml
  package.json
  yarn.lock
Labels: dependencies, enhancement

#111 Add a workflow for indexing
  .github/workflows/index.yml
Labels: enhancement

#112 Update the indexing workflow
  .github/workflows/index.yml
  yarn.lock
Labels: enhancement

#113 Update indexing env vars in the deploy workflow
  .github/workflows/deploy.yml
Labels: bug

#110 Update bulk-operations.md
  src/pages/development/components/message-queues/bulk-operations.md
Labels: technical

#86 Added information about passing variables in Widget template. Changed…
  src/pages/tutorials/frontend/create-custom-widget.md
Labels: technical

#117 Fix indexing workflow
  .github/workflows/index.yml
  yarn.lock
Labels: maintenance
