Repository AdobeDocs/commerce-php, pull requests merged in 2023-12, with the labels that each got.

#219 Update index.md
  src/pages/development/components/indexing/index.md
Labels: editorial

#222 Fix and update the test-pull-request workflow
  .github/workflows/test-pull-request.yml
  .nvmrc
  package.json
Labels: maintenance

#223 Fix and update workflows with a build step
  .github/workflows/github-pages.yml
  .github/workflows/index.yml
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance, internal

#224 Update testing workflow
  .github/workflows/github-pages.yml
  .github/workflows/index.yml
  .github/workflows/publish.yml
  .github/workflows/stage.yml
  .github/workflows/test-pull-request.yml
  package.json
Labels: maintenance, internal
