Repository AdobeDocs/commerce-php, pull requests merged in 2023-11, with the labels that each got.

#207 Fix indexing workflow
  .github/workflows/index.yml
Labels: bug, maintenance

#208 Update workflows with deployments
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#209 Sync deployment workflows with the template repo
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#210 Add definition of Model directories
  src/pages/development/build/component-file-structure.md
Labels: technical, internal

#212 Dropdown menu for the Module reference versions
  src/data/navigation/header.js
  yarn.lock
Labels: editorial, internal

#214 GH-213: Fixed broken link
  src/_includes/page-cache-checklist.md
  src/pages/development/cache/page/private-content.md
Labels: editorial, internal

#215 Add a linter to validate external links
  .remarkrc.mjs
  package.json
  src/pages/architecture/basics/security.md
  src/pages/best-practices/extensions/faq.md
  src/pages/best-practices/extensions/security.md
  src/pages/best-practices/phpstorm/run-configuration.md
  src/pages/best-practices/phpstorm/upgrade-compatibility-tool.md
  src/pages/best-practices/security/index.md
  src/pages/coding-standards/php.md
  src/pages/development/backward-incompatible-changes/highlights.md
  src/pages/development/build/composer-integration.md
  src/pages/development/build/dependency-injection-file.md
  src/pages/development/build/development-environment.md
  src/pages/development/components/indexing/index.md
  src/pages/development/components/web-api/inventory-management.md
  src/pages/development/payments-integrations/cardinal.md
  src/pages/development/security/non-secure-functions.md
  src/pages/development/versioning/index.md
  src/pages/development/versioning/tests.md
  src/pages/module-reference-beta/module-customer-graph-ql.md
  src/pages/module-reference-beta/module-instant-purchase.md
  src/pages/module-reference-beta/module-quote-graph-ql.md
  src/pages/module-reference-beta/module-wishlist-graph-ql.md
  src/pages/module-reference/module-media-gallery-api.md
  src/pages/tutorials/admin/create-admin-page.md
  src/pages/tutorials/backend/copy-fieldsets.md
  src/pages/tutorials/backend/create-custom-import-entity.md
  yarn.lock
Labels: enhancement

#216 Add validation for custom headers
  .github/workflows/test-pull-request.yml
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: enhancement, maintenance

#217 Update theme and caniuse-lite
  package.json
  yarn.lock
Labels: dependencies
