Repository AdobeDocs/commerce-php, pull requests merged in 2023-09, with the labels that each got.

#185 Update dependency-injection-file.md
  src/pages/development/build/dependency-injection-file.md
Labels: editorial

#191 Update URL of Magento Coding Standard repo
  src/pages/best-practices/extensions/security.md
Labels: editorial

#192 COMDOX-739: Added backward-incompatible changes highlights for 2.4.7-beta2
  src/pages/development/backward-incompatible-changes/highlights.md
Labels: major update, 2.4.7

#196 Remove broken site.data.var references
  src/pages/tutorials/backend/create-custom-rest-api.md
Labels: editorial, internal

#195 Missing onCreate attribute in "table" node decription
  src/pages/development/components/declarative-schema/configuration.md
Labels: technical
