Repository AdobeDocs/commerce-php, pull requests merged in 2023-04, with the labels that each got.

#134 COMDOX-596: Update gatsby-theme-aio to 4.9.0
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: maintenance, dependencies

#139 Use Shorthand Echo in XSS Code Blocks
  src/pages/development/security/cross-site-scripting.md
Labels: technical

#122 Remove `setup_version` attribute from `module.xml` example
  src/pages/development/build/component-load-order.md
Labels: technical

#143 Update convert-serialized-data.md
  src/pages/tutorials/backend/convert-serialized-data.md
Labels: editorial
