Repository AdobeDocs/commerce-php, pull requests merged in 2024-09, with the labels that each got.

#311 Fix Forced Params Anchor Link
  src/pages/development/components/web-api/services.md
Labels: editorial

#314 Don't run Add to project GH Action in forks
  .github/workflows/add-to-project_job.yml
Labels: maintenance

#316 COMDOX-1016: Backward-incompatible changes for 2.4.8-beta1
  src/pages/coding-standards/docblock.md
  src/pages/development/backward-incompatible-changes/highlights.md
Labels: major-update, 2.4.8
