Repository AdobeDocs/commerce-php, pull requests merged in 2024-08, with the labels that each got.

#295 ACP2E-3217: Adjust CSP documentation
  src/pages/development/security/content-security-policies.md
Labels: editorial, internal

#298 Fix broken link
  src/pages/development/cli-commands/index.md
Labels: editorial, internal

#299 ACP2E-3234: Improve CSP documentation
  src/pages/development/security/content-security-policies.md
Labels: editorial, internal

#306 Refactor GitHub Actions workflows
  .github/super-linter.env
  .github/workflows/github-pages.yml
  .github/workflows/index.yml
  .github/workflows/publish.yml
  .github/workflows/stage.yml
  .github/workflows/test-pull-request.yml
  src/pages/development/common-terms.md
  src/pages/development/prepare/development-roadmap.md
  src/pages/module-reference/module-adobe-commerce-events-client.md
  src/pages/module-reference/module-adobe-commerce-events-generator.md
Labels: maintenance, internal

#309 Add missing backward-incompatible changes
  src/_includes/backward-incompatible-changes/commerce/2.4.6-2.4.7.md
  src/_includes/backward-incompatible-changes/open-source/2.4.6-2.4.7.md
Labels: technical
