Repository AdobeDocs/commerce-php, pull requests merged in 2024-04, with the labels that each got.

#251 Upgrade theme to v4.11.9
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: internal, dependencies

#250 COMDOX-849: BIC highlights for 2.4.7 GA
  .remarkrc.mjs
  src/pages/development/backward-incompatible-changes/highlights.md
  src/pages/development/components/app-server.md
Labels: major-update, internal, 2.4.7

#245 [PCI] Documentation
  src/data/navigation/sections/development.js
  src/pages/_images/security/csp-report-uri.png
  src/pages/development/security/content-security-policies.md
  src/pages/development/security/index.md
  src/pages/development/security/subresource-integrity.md
Labels: new-topic, internal, 2.4.7

#253 Update async-topics.md
  src/pages/development/components/message-queues/async-topics.md
Labels: editorial

#256 Rebranded app server
  .remarkrc.mjs
  src/data/navigation/sections/development.js
  src/pages/development/components/app-server.md
Labels: editorial, internal, 2.4.7

#257 Update BIC highlights with note about otp_window
  src/pages/development/backward-incompatible-changes/highlights.md
Labels: dependencies, 2.4.7

#258 Update backward incompatible changes reference
  src/_includes/backward-incompatible-changes/b2b/2.4.6-2.4.7.md
  src/_includes/backward-incompatible-changes/commerce/2.4.6-2.4.7-beta1.md
  src/_includes/backward-incompatible-changes/commerce/2.4.6-2.4.7-beta2.md
  src/_includes/backward-incompatible-changes/commerce/2.4.6-2.4.7.md
  src/_includes/backward-incompatible-changes/open-source/2.4.6-2.4.7-beta1.md
  src/_includes/backward-incompatible-changes/open-source/2.4.6-2.4.7.md
  src/pages/development/backward-incompatible-changes/reference.md
Labels: major-update, 2.4.7

#261 ACP2E-3031: Update the documentation on OM in templates
  src/pages/coding-standards/technical-guidelines.md
Labels: major-update, internal

#260 COMDOX-908: Update Module reference
  src/pages/module-reference/module-scalable-checkout.md
  src/pages/module-reference/module-scalable-inventory.md
  src/pages/module-reference/module-scalable-oms.md
Labels: technical, internal
