Repository AdobeDocs/commerce-php, pull requests merged in 2024-06, with the labels that each got.

#274 COMDOX-968: Render Adobe Commerce sections with Adobe Commerce B2B data
  src/_includes/backward-incompatible-changes/b2b/2.4.0-2.4.1.md
  src/_includes/backward-incompatible-changes/b2b/2.4.1-2.4.2.md
  src/_includes/backward-incompatible-changes/b2b/2.4.2-2.4.3.md
  src/_includes/backward-incompatible-changes/b2b/2.4.3-2.4.3-p1.md
  src/_includes/backward-incompatible-changes/b2b/2.4.3-2.4.4.md
  src/_includes/backward-incompatible-changes/b2b/2.4.4-2.4.5.md
  src/_includes/backward-incompatible-changes/b2b/2.4.5-2.4.6.md
  src/_includes/backward-incompatible-changes/b2b/2.4.6-2.4.7.md
  src/_includes/backward-incompatible-changes/commerce/2.4.5-2.4.6.md
  src/_includes/backward-incompatible-changes/commerce/2.4.6-2.4.7.md
  src/pages/development/backward-incompatible-changes/reference.md
  src/pages/module-reference/module-new-relic-reporting.md
Labels: technical

#277 Update web-api.md changed the area from webapi_graphql to graphql
  src/pages/architecture/technical-vision/web-api.md
Labels: technical

#278 Upgrade theme to v4.11.14
  .remarkrc.mjs
  package.json
  src/pages/architecture/basics/security.md
  src/pages/development/validate/test-component.md
  yarn.lock
Labels: internal, dependencies

#276 Update Backward incompatible changes reference reports
  .remarkrc.mjs
  src/_includes/backward-incompatible-changes/commerce/2.4.7-2.4.7-p1.md
  src/_includes/backward-incompatible-changes/open-source/2.4.7-2.4.7-p1.md
  src/pages/development/backward-incompatible-changes/reference.md
Labels: technical, devops

#280 Revert "Update Backward incompatible changes reference reports"
  .remarkrc.mjs
  src/_includes/backward-incompatible-changes/commerce/2.4.7-2.4.7-p1.md
  src/_includes/backward-incompatible-changes/open-source/2.4.7-2.4.7-p1.md
  src/pages/development/backward-incompatible-changes/reference.md
Labels: bug
