Repository AdobeDocs/commerce-php, pull requests merged in 2024-02, with the labels that each got.

#231 Fix typo in api-concepts.md
  src/pages/development/components/api-concepts.md
Labels: editorial

#232 Update composer-integration.md
  src/pages/development/build/composer-integration.md
Labels: editorial, Waiting for Response

#237 Sync 2.4.7-develop w/ main
  .github/workflows/github-pages.yml
  .github/workflows/index.yml
  .github/workflows/publish.yml
  .github/workflows/stage.yml
  .github/workflows/test-pull-request.yml
  .nvmrc
  .remarkrc.mjs
  package.json
  src/_includes/page-cache-checklist.md
  src/data/navigation/header.js
  src/pages/architecture/basics/security.md
  src/pages/best-practices/extensions/faq.md
  src/pages/best-practices/extensions/security.md
  src/pages/best-practices/phpstorm/run-configuration.md
  src/pages/best-practices/phpstorm/upgrade-compatibility-tool.md
  src/pages/best-practices/security/index.md
  src/pages/coding-standards/php.md
  src/pages/development/backward-incompatible-changes/highlights.md
  src/pages/development/build/component-file-structure.md
  src/pages/development/build/composer-integration.md
  src/pages/development/build/dependency-injection-file.md
  src/pages/development/build/development-environment.md
  src/pages/development/cache/page/private-content.md
  src/pages/development/components/api-concepts.md
  src/pages/development/components/events-and-observers/index.md
  src/pages/development/components/indexing/index.md
  src/pages/development/components/web-api/inventory-management.md
  src/pages/development/payments-integrations/cardinal.md
  src/pages/development/security/non-secure-functions.md
  src/pages/development/versioning/index.md
  src/pages/development/versioning/tests.md
  src/pages/module-reference-beta/module-customer-graph-ql.md
  src/pages/module-reference-beta/module-instant-purchase.md
  src/pages/module-reference-beta/module-quote-graph-ql.md
  src/pages/module-reference-beta/module-wishlist-graph-ql.md
  src/pages/module-reference/module-media-gallery-api.md
  src/pages/tutorials/admin/create-admin-page.md
  src/pages/tutorials/backend/copy-fieldsets.md
  src/pages/tutorials/backend/create-custom-import-entity.md
  src/pages/tutorials/backend/modify-image-library-permissions.md
  yarn.lock
Labels: maintenance, internal

#238 COMDOX-818: 2.4.7-beta3 BIC highlights
  src/pages/development/backward-incompatible-changes/highlights.md
Labels: major-update, internal, 2.4.7-beta3
