Repository AdobeDocs/commerce-php, pull requests merged in 2024-07, with the labels that each got.

#288 Small commit to force update on integration branch
  src/pages/development/backward-incompatible-changes/highlights.md
Labels: editorial, internal

#287 Add links to additional release resources
  src/pages/development/backward-incompatible-changes/index.md
Labels: editorial, internal

#292 Upgrade devDependencies
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: dependencies

#293 Enable indexing on deploy
  .github/workflows/index.yml
  .github/workflows/publish.yml
Labels: maintenance, internal
