Repository AdobeDocs/commerce-php, pull requests merged in 2024-03, with the labels that each got.

#236 COMDOX-906: Extension compatibility with Application Server
  src/data/navigation/sections/development.js
  src/pages/best-practices/security/index.md
  src/pages/coding-standards/jquery-widgets.md
  src/pages/coding-standards/js.md
  src/pages/development/components/app-server.md
  src/pages/development/security/non-secure-functions.md
Labels: new-topic, internal, 2.4.7-beta3

#246 Corrected 2.4.7-beta3 BIC highlight
  src/pages/development/backward-incompatible-changes/highlights.md
Labels: editorial

#226 Update price-adjustments.md
  src/pages/development/components/price-adjustments.md
Labels: major-update

#243 fix reasons for incompatibility with Application server
  src/pages/development/components/app-server.md
Labels: editorial, internal, 2.4.7-beta3
