Repository AdobeDocs/commerce-php, pull requests merged in 2025-03, with the labels that each got.

#354 AC-14137: SRI docs update.
  src/pages/development/security/subresource-integrity.md
Labels: technical, internal, 2.4.8

#357 Enable suggested fixes for Markdown
  .github/super-linter.env
  .github/workflows/test-pull-request.yml
  .github/workflows/validate-pr_job.yml
  .gitignore
Labels: maintenance

#361 COMDOX-1167: Remove references to 2.4.8-beta
  src/pages/development/components/app-server.md
Labels: maintenance, 2.4.8
