Repository AdobeDocs/commerce-php, pull requests merged in 2025-02, with the labels that each got.

#343 Fix links
  .remarkrc.mjs
  src/pages/development/backward-incompatible-changes/highlights.md
  src/pages/development/payments-integrations/cardinal.md
Labels: editorial

#341 February 2025 release (2.4.8-beta2)
  .remarkrc.mjs
  src/_includes/notes/beta.md
  src/data/navigation/sections/development.js
  src/pages/coding-standards/technical-guidelines.md
  src/pages/development/backward-incompatible-changes/highlights.md
  src/pages/development/payments-integrations/cardinal.md
  src/pages/development/security/data-encryption.md
  src/pages/tutorials/backend/create-api-integration.md
Labels: maintenance, internal

#344 Cover Backward incompatible changes 2.4.8-beta1 - 2.4.8-beta2
  src/_includes/backward-incompatible-changes/commerce/2.4.8-beta1-2.4.8-beta2.md
  src/_includes/backward-incompatible-changes/open-source/2.4.8-beta1-2.4.8-beta2.md
  src/pages/development/backward-incompatible-changes/reference.md
Labels: major-update, 2.4.8

#345 fix: remove beta note from data encryption topic
  src/pages/development/security/data-encryption.md
Labels: editorial, internal

#346 Enable linter VALIDATE_GIT_MERGE_CONFLICT_MARKERS
  .github/CODE_OF_CONDUCT.md
  .github/super-linter.env
  .github/workflows/test-pull-request.yml
Labels: maintenance

#349 Update GitHub workflows
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance, internal

#351 Convert test-pull-request workflow to reusable
  .github/workflows/add-to-project-board.yml
  .github/workflows/github-pages.yml
  .github/workflows/test-pull-request.yml
  .github/workflows/validate-pr_job.yml
Labels: maintenance
